i <- 1
v <- "LM2_sepN2500_50k"
id <- i
J <- 100
Nj <- 25
nalpha <- 11
source("~/OhnishiExtensionCode/Data_Simulation_LM2.R")
beta <- readRDS(paste0("~/palmer_scratch/OhnishiExtension/Results/", v, "/beta", i, ".rds"))
sig <- readRDS(paste0("~/palmer_scratch/OhnishiExtension/Results/", v, "/sigma2", i, ".rds"))
beta1.df <- do.call("rbind", lapply(beta, function(x) x[,1]))
beta2.df <- do.call("rbind", lapply(beta, function(x) x[,2]))
beta3.df <- do.call("rbind", lapply(beta, function(x) x[,3]))
beta4.df <- do.call("rbind", lapply(beta, function(x) x[,4]))
beta5.df <- do.call("rbind", lapply(beta, function(x) x[,5]))
sig.df <- do.call("rbind", sig)
G <- readRDS(paste0("~/palmer_scratch/OhnishiExtension/Results/", v, "/G", i, ".rds"))
G.df <- do.call("rbind", (lapply(G, function(x) c(x))))
mcmc.pars <- array(data = NA, dim = c(10000, 6, 6))
mcmc.pars[,,1] <- beta1.df
mcmc.pars[,,2] <- beta2.df
mcmc.pars[,,3] <- beta3.df
mcmc.pars[,,4] <- beta4.df
mcmc.pars[,,5] <- beta5.df
mcmc.pars[,,6] <- sig.df
labs <- label.switching(c("AIC", "DATA-BASED", "ECR-ITERATIVE-1"), z=G.df[iters,], K=6, mcmc=mcmc.pars[iters,,], data=Y_long)
pm <- permute.mcmc(mcmc.pars, labs$permutations$AIC)

par(mfrow=c(5,2), mar=c(2,4,2,2))
plot(0, xlim=c(1, 10000), ylim=c(-20,20), type='n', ylab="Beta1")
lines(unlist(lapply(beta, function(x) x[6,1])), type='l', col='purple3')
lines(unlist(lapply(beta, function(x) x[5,1])), type='l', col='blue3')
lines(unlist(lapply(beta, function(x) x[4,1])), type='l', col='green3')
lines(unlist(lapply(beta, function(x) x[3,1])), type='l', col='yellow3')
lines(unlist(lapply(beta, function(x) x[2,1])), type='l', col='orange3')
lines(unlist(lapply(beta, function(x) x[1,1])), type='l', col='red3')
abline(h=beta_true[6,1], col='purple', lwd=2, lty=2)
abline(h=beta_true[5,1], col='blue', lwd=2, lty=2)
abline(h=beta_true[4,1], col='green', lwd=2, lty=2)
abline(h=beta_true[3,1], col='yellow', lwd=2, lty=2)
abline(h=beta_true[2,1], col='orange', lwd=2, lty=2)
abline(h=beta_true[1,1], col='red', lwd=2, lty=2)
plot(0, xlim=c(1, 10000), ylim=c(-20,15), type='n', ylab="Beta1")
lines(pm$output[,1,1], type='l', col='red3')
lines(pm$output[,2,1], type='l', col='orange3')
lines(pm$output[,3,1], type='l', col='yellow3')
lines(pm$output[,4,1], type='l', col='green3')
lines(pm$output[,5,1], type='l', col='blue3')
lines(pm$output[,6,1], type='l', col='purple3')
abline(h=beta_true[6,1], col='purple', lwd=2, lty=2)
abline(h=beta_true[5,1], col='blue', lwd=2, lty=2)
abline(h=beta_true[4,1], col='green', lwd=2, lty=2)
abline(h=beta_true[3,1], col='yellow', lwd=2, lty=2)
abline(h=beta_true[2,1], col='orange', lwd=2, lty=2)
abline(h=beta_true[1,1], col='red', lwd=2, lty=2)

plot(0, xlim=c(1, 10000), ylim=c(-20,20), type='n', ylab="Beta2", xlab="")
lines(unlist(lapply(beta, function(x) x[6,2])), type='l', col='purple3')
lines(unlist(lapply(beta, function(x) x[5,2])), type='l', col='blue3')
lines(unlist(lapply(beta, function(x) x[4,2])), type='l', col='green3')
lines(unlist(lapply(beta, function(x) x[3,2])), type='l', col='yellow3')
lines(unlist(lapply(beta, function(x) x[2,2])), type='l', col='orange3')
lines(unlist(lapply(beta, function(x) x[1,2])), type='l', col='red3')
abline(h=beta_true[6,2], col='purple', lwd=2, lty=2)
abline(h=beta_true[5,2], col='blue', lwd=2, lty=2)
abline(h=beta_true[4,2], col='green', lwd=2, lty=2)
abline(h=beta_true[3,2], col='yellow', lwd=2, lty=2)
abline(h=beta_true[2,2], col='orange', lwd=2, lty=2)
abline(h=beta_true[1,2], col='red', lwd=2, lty=2)
plot(0, xlim=c(1, 10000), ylim=c(-15,15), type='n', ylab="Beta2", xlab="")
lines(pm$output[,1,2], type='l', col='red3')
lines(pm$output[,2,2], type='l', col='orange3')
lines(pm$output[,3,2], type='l', col='yellow3')
lines(pm$output[,4,2], type='l', col='green3')
lines(pm$output[,5,2], type='l', col='blue3')
lines(pm$output[,6,2], type='l', col='purple3')
abline(h=beta_true[6,2], col='purple', lwd=2, lty=2)
abline(h=beta_true[5,2], col='blue', lwd=2, lty=2)
abline(h=beta_true[4,2], col='green', lwd=2, lty=2)
abline(h=beta_true[3,2], col='yellow', lwd=2, lty=2)
abline(h=beta_true[2,2], col='orange', lwd=2, lty=2)
abline(h=beta_true[1,2], col='red', lwd=2, lty=2)

plot(0, xlim=c(1, 10000), ylim=c(-30,30), type='n', ylab="Beta3",xlab="")
lines(unlist(lapply(beta, function(x) x[1,3])), type='l', col=('red3'))
lines(unlist(lapply(beta, function(x) x[2,3])), type='l', col=('orange3'))
lines(unlist(lapply(beta, function(x) x[6,3])), type='l', col=('purple3'))
lines(unlist(lapply(beta, function(x) x[5,3])), type='l', col=('blue3'))
lines(unlist(lapply(beta, function(x) x[4,3])), type='l', col=('green3'))
lines(unlist(lapply(beta, function(x) x[3,3])), type='l', col=('yellow3'))
abline(h=beta_true[6,3], col='purple', lwd=2, lty=2)
abline(h=beta_true[5,3], col='blue', lwd=2, lty=2)
abline(h=beta_true[4,3], col='green', lwd=2, lty=2)
abline(h=beta_true[3,3], col='yellow', lwd=2, lty=2)
abline(h=beta_true[2,3], col='orange', lwd=2, lty=2)
abline(h=beta_true[1,3], col='red', lwd=2, lty=2)
plot(0, xlim=c(1, 10000), ylim=c(-20,25), type='n', ylab="Beta3", xlab="")
lines(pm$output[,1,3], type='l', col='red3')
lines(pm$output[,2,3], type='l', col='orange3')
lines(pm$output[,3,3], type='l', col='yellow3')
lines(pm$output[,4,3], type='l', col='green3')
lines(pm$output[,5,3], type='l', col='blue3')
lines(pm$output[,6,3], type='l', col='purple3')
abline(h=beta_true[6,3], col='purple', lwd=2, lty=2)
abline(h=beta_true[5,3], col='blue', lwd=2, lty=2)
abline(h=beta_true[4,3], col='green', lwd=2, lty=2)
abline(h=beta_true[3,3], col='yellow', lwd=2, lty=2)
abline(h=beta_true[2,3], col='orange', lwd=2, lty=2)
abline(h=beta_true[1,3], col='red', lwd=2, lty=2)

plot(0, xlim=c(1, 10000), ylim=c(-30,30), type='n', ylab="Beta4", xlab="")
lines(unlist(lapply(beta, function(x) x[1,4])), type='l', col=('red3'))
lines(unlist(lapply(beta, function(x) x[2,4])), type='l', col=('orange3'))
lines(unlist(lapply(beta, function(x) x[6,4])), type='l', col=('purple3'))
lines(unlist(lapply(beta, function(x) x[5,4])), type='l', col=('blue3'))
lines(unlist(lapply(beta, function(x) x[4,4])), type='l', col=('green3'))
lines(unlist(lapply(beta, function(x) x[3,4])), type='l', col=('yellow3'))
abline(h=beta_true[6,4], col='purple', lwd=2, lty=2)
abline(h=beta_true[5,4], col='blue', lwd=2, lty=2)
abline(h=beta_true[4,4], col='green', lwd=2, lty=2)
abline(h=beta_true[3,4], col='yellow', lwd=2, lty=2)
abline(h=beta_true[2,4], col='orange', lwd=2, lty=2)
abline(h=beta_true[1,4], col='red', lwd=2, lty=2)
plot(0, xlim=c(1, 10000), ylim=c(-20,15), type='n', ylab="Beta4", xlab="")
lines(pm$output[,1,4], type='l', col='red3')
lines(pm$output[,2,4], type='l', col='orange3')
lines(pm$output[,3,4], type='l', col='yellow3')
lines(pm$output[,4,4], type='l', col='green3')
lines(pm$output[,5,4], type='l', col='blue3')
lines(pm$output[,6,4], type='l', col='purple3')
abline(h=beta_true[6,4], col='purple', lwd=2, lty=2)
abline(h=beta_true[5,4], col='blue', lwd=2, lty=2)
abline(h=beta_true[4,4], col='green', lwd=2, lty=2)
abline(h=beta_true[3,4], col='yellow', lwd=2, lty=2)
abline(h=beta_true[2,4], col='orange', lwd=2, lty=2)
abline(h=beta_true[1,4], col='red', lwd=2, lty=2)

plot(0, xlim=c(1, 10000), ylim=c(-30,30), type='n', ylab="Beta5", xlab="")
lines(unlist(lapply(beta, function(x) x[1,5])), type='l', col=('red3'))
lines(unlist(lapply(beta, function(x) x[2,5])), type='l', col=('orange3'))
lines(unlist(lapply(beta, function(x) x[6,5])), type='l', col=('purple3'))
lines(unlist(lapply(beta, function(x) x[5,5])), type='l', col=('blue3'))
lines(unlist(lapply(beta, function(x) x[4,5])), type='l', col=('green3'))
lines(unlist(lapply(beta, function(x) x[3,5])), type='l', col=('yellow3'))
abline(h=beta_true[6,5], col='purple', lwd=2, lty=2)
abline(h=beta_true[5,5], col='blue', lwd=2, lty=2)
abline(h=beta_true[4,5], col='green', lwd=2, lty=2)
abline(h=beta_true[3,5], col='yellow', lwd=2, lty=2)
abline(h=beta_true[2,5], col='orange', lwd=2, lty=2)
abline(h=beta_true[1,5], col='red', lwd=2, lty=2)
plot(0, xlim=c(1, 10000), ylim=c(-5,15), type='n', ylab="Beta5", xlab="")
lines(pm$output[,1,5], type='l', col='red3')
lines(pm$output[,2,5], type='l', col='orange3')
lines(pm$output[,3,5], type='l', col='yellow3')
lines(pm$output[,4,5], type='l', col='green3')
lines(pm$output[,5,5], type='l', col='blue3')
lines(pm$output[,6,5], type='l', col='purple3')
abline(h=beta_true[6,5], col='purple', lwd=2, lty=2)
abline(h=beta_true[5,5], col='blue', lwd=2, lty=2)
abline(h=beta_true[4,5], col='green', lwd=2, lty=2)
abline(h=beta_true[3,5], col='yellow', lwd=2, lty=2)
abline(h=beta_true[2,5], col='orange', lwd=2, lty=2)
abline(h=beta_true[1,5], col='red', lwd=2, lty=2)